supabase_url = "https://hrjbibhasktaxglnccwk.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyamJpYmhhc2t0YXhnbG5jY3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTYwOTc3MDQsImV4cCI6MTk3MTY3MzcwNH0.TY-Xa1VIcKAYyrHdVIf888gri_M451XJqqr9AyvKaNc"

test_email = 'dnoell@ppeng.com'
test_password = 'denver-admin-password'

cimis_key = '437431d3-4742-4f71-a46e-c51e87465f0c'

['NOAA']
token='bDAYdHnrMpAjFMztbJazmCBLtGWBOcTn'

['Notion']
token='secret_FlsHKgma9UlfMabmztzCSkacOy343dLw5U8ZTv3Astk'

['Sentinel']
user_id = '85209a4b-f4a4-48f8-8fc1-85adffc6266f'

['Ag Water Supabase Postgres']
host='db.hrjbibhasktaxglnccwk.supabase.co'
database='postgres'
username='postgres'
password="6No$d^gDWKapssyZpwmc"
port='5432'

['Microsoft Graph']
app_name = 'Graph Python quick start'
client_id = 'b30de8ff-09fc-40ef-b2d5-76a438f331a0'

['github']
token = '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'

['github_org']
client_id = 'de569dedaf405e7fc372'
token = "47aaa9b10c84dd709fad4330fbabe8b76173aaf2"

# Clovis IP 50.201.113.238
['Denver Email']
username = "dnoell@ppeng.com"
password = "Velocity6"
smtp = 'smtp-mail.outlook.com'
port = 587

['Denver ESRI']
username = "dnoell@ppeng.com"
# password = "3LHxttUn$eUC&Tmy#C9^"
password = "Ptdq7&r%$i"

['mapbox']
token='pk.eyJ1IjoiZGVudmVyLW5vZWxsIiwiYSI6ImNsbHY0aWV3dDAyMmozcHBrbTZmbjQwNXgifQ.5FLAB31RJ4VXu7fd830qMA'